addons:
  code_climate:
    repo_token: 85f5d9d91bf3d3b6e75953af01542b7673b93e860056238fc28714085570e4c2
dist: trusty
sudo: required
language: node_js
node_js:
  - "5"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  - sh -e /etc/init.d/xvfb start
  - npm install -g gulp
  - npm install -g bower
install:
  - npm install
script:
  - gulp
  - npm run lint
  - npm run test:once
  - npm run e2e
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
